// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const createComputed: typeof import('solid-js')['createComputed']
  const createEffect: typeof import('solid-js')['createEffect']
  const createMemo: typeof import('solid-js')['createMemo']
  const createSignal: typeof import('solid-js')['createSignal']
  const createStore: typeof import('solid-js/store')['createStore']
  const For: typeof import('solid-js')['For']
  const on: typeof import('solid-js')['on']
  const Show: typeof import('solid-js')['Show']
  const Suspense: typeof import('solid-js')['Suspense']
  const useData: typeof import('solid-app-router')['useData']
  const useNavigate: typeof import('solid-app-router')['useNavigate']
  const useParams: typeof import('solid-app-router')['useParams']
}
export {}
